### ISSUE TITLE
Feature request: Follow node.role == manager constraint

### ISSUE THREAD

**Issue by yukiisbored** [tiangolo/docker-auto-labels#1]
* Docker Auto Labels version: v0.2.2
* Python version: Python 3.8.2
* Operating System: Debian 10 Buster

### Description

docker-auto-labels should follow the `node.role == manager` constraint. When present, it should assign the labels only to the manager nodes inside the cluster.

**Comment by tiangolo** [comment]
Thanks for the suggestion, unfortunately, I'm no longer using this, and I wouldn't be able to add the feature and support it.

So I'll pass on this, but thanks for the interest! :coffee:
