### ISSUE TITLE
YAMLLoadWarning: ... the default Loader is unsafe

### ISSUE THREAD

**Issue by jayvdb** [tiangolo/docker-auto-labels#3]
* Docker Auto Labels version: 0.2.3
* Python version: 3.8
* Operating System: Ubunutu

### Description

On startup the following is show

```
/usr/lib/python3.8/site-packages/docker_auto_labels/docker_auto_labels.py:16: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(docker_file)
```

**Comment by MrYutz** [comment]
I can confirm changing the function to `yaml.safe_load()` fixes this.

**Comment by tiangolo** [comment]
Thanks! This was handled as part of https://github.com/tiangolo/docker-auto-labels/pull/11
